[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx prisma generate", "bun build src/index.ts --outdir=dist --target=bun"]

[start]
cmd = "bun run dist/index.js"
